import { describe,it,expect,beforeEach } from 'vitest';
import request from 'supertest';
import express from 'express';
import router from '../src/routes';
import { runSql, flushDb } from '../src/db';

function app(){const a=express();a.use(express.json({limit:'10mb'}));a.use('/api',router);return a}
function clear(){runSql('DELETE FROM bookmarks');runSql('DELETE FROM tiles');runSql('DELETE FROM categories');}

describe('hierarchical bookmark manager',()=>{
 beforeEach(clear);
 it('supports category CRUD and persistent collapse state',async()=>{const a=app();const c=await request(a).post('/api/categories').send({name:'Spaceweather'});expect(c.status).toBe(201);const id=c.body.id;const u=await request(a).put(`/api/categories/${id}`).send({name:'Space Weather',collapsed:1});expect(u.body).toMatchObject({name:'Space Weather',collapsed:1});const g=await request(a).get('/api/hierarchy');expect(g.body.categories[0]).toMatchObject({id,name:'Space Weather',collapsed:1});});
 it('sorts categories server-side',async()=>{const a=app();const x=await request(a).post('/api/categories').send({name:'A'});const y=await request(a).post('/api/categories').send({name:'B'});await request(a).put('/api/hierarchy/layout').send({categories:[{id:x.body.id,sort_order:1},{id:y.body.id,sort_order:0}]});const g=await request(a).get('/api/hierarchy');expect(g.body.categories.map((c:{name:string})=>c.name)).toEqual(['B','A']);});
 it('supports tile CRUD, sorting and moving between categories',async()=>{const a=app();const c1=await request(a).post('/api/categories').send({name:'One'});const c2=await request(a).post('/api/categories').send({name:'Two'});const t1=await request(a).post('/api/tiles').send({category_id:c1.body.id,name:'T1'});const t2=await request(a).post('/api/tiles').send({category_id:c1.body.id,name:'T2'});await request(a).put('/api/hierarchy/layout').send({tiles:[{id:t1.body.id,category_id:c1.body.id,sort_order:1,position_x:null,position_y:null},{id:t2.body.id,category_id:c1.body.id,sort_order:0,position_x:null,position_y:null}]});await request(a).put(`/api/tiles/${t1.body.id}`).send({category_id:c2.body.id});const g=await request(a).get('/api/hierarchy');expect(g.body.tiles.find((t:{id:number})=>t.id===t1.body.id).category_id).toBe(c2.body.id);expect(g.body.tiles.filter((t:{category_id:number})=>t.category_id===c1.body.id).map((t:{name:string})=>t.name)).toEqual(['T2']);});
 it('supports bookmark CRUD, favicon data URIs and sorting',async()=>{const a=app();const c=await request(a).post('/api/categories').send({name:'Wetter'});const t=await request(a).post('/api/tiles').send({category_id:c.body.id,name:'Radar'});const b1=await request(a).post('/api/bookmarks').send({tile_id:t.body.id,name:'A',url:'https://a.example',favicon:'data:image/png;base64,AAAA'});const b2=await request(a).post('/api/bookmarks').send({tile_id:t.body.id,name:'B',url:'https://b.example'});await request(a).put('/api/hierarchy/layout').send({bookmarks:[{id:b1.body.id,tile_id:t.body.id,sort_order:1},{id:b2.body.id,tile_id:t.body.id,sort_order:0}]});const g=await request(a).get('/api/hierarchy');expect(g.body.bookmarks[0].name).toBe('B');expect(g.body.bookmarks.find((b:{id:number})=>b.id===b1.body.id).favicon).toContain('data:image/png;base64');});
 it('moves bookmarks between tiles without deleting them',async()=>{const a=app();const c=await request(a).post('/api/categories').send({name:'C'});const t1=await request(a).post('/api/tiles').send({category_id:c.body.id,name:'T1'});const t2=await request(a).post('/api/tiles').send({category_id:c.body.id,name:'T2'});const b=await request(a).post('/api/bookmarks').send({tile_id:t1.body.id,name:'Keep',url:'https://keep.example'});await request(a).put(`/api/bookmarks/${b.body.id}`).send({tile_id:t2.body.id});const g=await request(a).get('/api/hierarchy');expect(g.body.bookmarks).toHaveLength(1);expect(g.body.bookmarks[0].tile_id).toBe(t2.body.id);});
 it('imports Brave-shaped hierarchy additively and de-duplicates URLs',async()=>{const a=app();const c=await request(a).post('/api/categories').send({name:'Wetter'});const t=await request(a).post('/api/tiles').send({category_id:c.body.id,name:'Radar'});await request(a).post('/api/bookmarks').send({tile_id:t.body.id,name:'Old',url:'https://same.example'});const r=await request(a).post('/api/hierarchy/import/brave').send({categories:[{name:'Wetter',sort_order:0,tiles:[{name:'Radar',sort_order:0,bookmarks:[{name:'New name',url:'https://same.example',favicon:'data:image/png;base64,AAAA',sort_order:0},{name:'Added',url:'https://added.example',sort_order:1}]}]}]});expect(r.body).toMatchObject({categoriesAdded:0,tilesAdded:0,bookmarksAdded:1,bookmarksUpdated:1});const g=await request(a).get('/api/hierarchy');expect(g.body.bookmarks).toHaveLength(2);expect(g.body.bookmarks.find((b:{url:string})=>b.url==='https://same.example').name).toBe('New name');});
 it('persists the database to disk after hierarchy changes',async()=>{const a=app();await request(a).post('/api/categories').send({name:'Persistent'});flushDb();const g=await request(a).get('/api/hierarchy');expect(g.body.categories[0].name).toBe('Persistent');});
 it('deletes a category with its descendants',async()=>{const a=app();const c=await request(a).post('/api/categories').send({name:'Delete'});const t=await request(a).post('/api/tiles').send({category_id:c.body.id,name:'T'});await request(a).post('/api/bookmarks').send({tile_id:t.body.id,name:'B',url:'https://delete.example'});await request(a).delete(`/api/categories/${c.body.id}`);const g=await request(a).get('/api/hierarchy');expect(g.body.categories).toHaveLength(0);expect(g.body.tiles).toHaveLength(0);expect(g.body.bookmarks).toHaveLength(0);});
});
